title: .KIT
description: Scratchのプロジェクト拡張をより簡単に
theme: just-the-docs

url: https://nekogakure.github.io/dotKIT/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
